import React from 'react';

import { Table, Tbody, Tr, Td, Text  } from '@chakra-ui/react'

function TblProfile(data) {
  return (
      <>
        <Table>
            <Tbody>
                <Tr>
                    <Td>
                        <Text>
                            เลขที่ตำแหน่ง
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            ชื่อ-สกุล(TH)
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            ชื่อ-สกุล(EN)
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            ประเภทบุคลากร
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            สายงาน
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            ตำแหน่งงาน
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            ตำแหน่งทางวิชาการ
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            ตำแหน่งบริหาร
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            วันที่เข้าทำงาน
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            วันที่บรรจุ
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            สถานะปฏิบัติงาน
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            วันเดือนปีเกิด
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            สัญชาติ
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            ศาสนา
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            เบอร์โทร
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            อีเมล ม.พะเยา
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            อีเมล ส่วนตัว
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
                <Tr>
                    <Td>
                        <Text>
                            ที่อยู่ปัจจุบัน
                        </Text>
                    </Td>
                    <Td>
                        <Text>
                            a
                        </Text>
                    </Td>
                </Tr>
            </Tbody>
        </Table>
      </>
  );
}

export {TblProfile};
